title: "Portfolio SQLTemp Cybersécurité"
description: "Projets, analyses, CTFs et notes de cours"

# IMPORTANT : adapter à ton domaine custom
url: "https://www.sqltemp.com"
baseurl: ""   # vide, puisque ton site est servi à la racine du domaine
author: Solutions SQLTemp Cybersécurité
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
collections:
  projects:
    output: true
    permalink: /projects/:title/
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      sidebar: true
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
sass:
  sass_dir: assets/css
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
include:
  - ".well-known"

# === OPTIONS SEO / MISE EN PAGE ===
social_links:
  github: https://sqltemp.github.io/portfolio/
  linkedin: https://www.linkedin.com/in/thierrymatrat/
  email: contact@sqltemp.com

paginate: 8
paginate_path: "/articles/page:num"
